on: [push, pull_request]

jobs:
  norminette_job:
    runs-on: ubuntu-latest
    name: norminette
    steps:
    - uses: actions/checkout@v2
    - run: python3 -m pip install --upgrade pip setuptools
    - run: python3 -m pip install norminette
    - run: norminette .
